version: '2.1'
services:
  yarb:
    build: .
    #restart: on-failure
    networks:
      - backend
    env_file:
      - ./.env
    volumes:
      - ./db.json:/db.json
        #stdin_open: true
        #tty: true
networks:
  backend:
    driver: bridge
